# Generated by Django 3.0.4 on 2020-03-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='genre',
            new_name='gender',
        ),
    ]
