# Generated by Django 3.0.4 on 2020-03-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='genre',
            new_name='gender',
        ),
    ]
